import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web application project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={inter.className} 
        style={{overflow: 'hidden', backgroundImage: 'linear-gradient(to top right, #03fcfc, #fc05e4 )'}}
      >
        {children}
      </body>
    </html>
  );
}
